// GENERATED by build_dungeon_atlas.py - DCSS/RLTiles (public domain / CC0) dungeon tileset manifest.
// Local ids are 0-based within dungeon.png; global gid = firstGid + localId.
const DUNGEON_TILESET = {
  "firstGid": 541,
  "tileCount": 185,
  "columns": 16,
  "names": {
    "floor_stone_0": 0,
    "floor_stone_1": 1,
    "floor_stone_2": 2,
    "floor_stone_3": 3,
    "floor_stone_4": 4,
    "floor_stone_5": 5,
    "floor_stone_6": 6,
    "floor_stone_7": 7,
    "floor_stone_8": 8,
    "floor_grey_0": 9,
    "floor_grey_1": 10,
    "floor_grey_2": 11,
    "floor_grey_3": 12,
    "floor_grey_4": 13,
    "floor_grey_5": 14,
    "floor_grey_6": 15,
    "floor_grey_7": 16,
    "floor_crypt_0": 17,
    "floor_crypt_1": 18,
    "floor_crypt_2": 19,
    "floor_crypt_3": 20,
    "floor_crypt_4": 21,
    "floor_crypt_5": 22,
    "floor_crypt_6": 23,
    "floor_crypt_7": 24,
    "floor_sand_0": 25,
    "floor_sand_1": 26,
    "floor_sand_2": 27,
    "floor_sand_3": 28,
    "floor_sand_4": 29,
    "floor_sand_5": 30,
    "floor_sand_6": 31,
    "floor_sand_7": 32,
    "floor_sand_8": 33,
    "floor_sand_9": 34,
    "floor_volcanic_0": 35,
    "floor_volcanic_1": 36,
    "floor_volcanic_2": 37,
    "floor_volcanic_3": 38,
    "floor_volcanic_4": 39,
    "floor_volcanic_5": 40,
    "floor_volcanic_6": 41,
    "floor_marsh_0": 42,
    "floor_marsh_1": 43,
    "floor_marsh_2": 44,
    "floor_marsh_3": 45,
    "floor_mud_0": 46,
    "floor_mud_1": 47,
    "floor_mud_2": 48,
    "floor_mud_3": 49,
    "floor_ice_0": 50,
    "floor_ice_1": 51,
    "floor_ice_2": 52,
    "floor_ice_3": 53,
    "floor_lair_0": 54,
    "floor_lair_1": 55,
    "floor_lair_2": 56,
    "floor_lair_3": 57,
    "floor_blood_0": 58,
    "floor_blood_1": 59,
    "floor_blood_2": 60,
    "floor_blood_3": 61,
    "floor_dirt_0": 62,
    "floor_dirt_1": 63,
    "floor_dirt_2": 64,
    "floor_marble_0": 65,
    "floor_marble_1": 66,
    "floor_marble_2": 67,
    "floor_marble_3": 68,
    "floor_marble_4": 69,
    "floor_marble_5": 70,
    "floor_tomb_0": 71,
    "floor_tomb_1": 72,
    "floor_tomb_2": 73,
    "floor_tomb_3": 74,
    "liquid_water_shallow": 75,
    "liquid_water_deep": 76,
    "liquid_water_murky": 77,
    "wall_brick_0": 78,
    "wall_brick_1": 79,
    "wall_brick_2": 80,
    "wall_brick_3": 81,
    "wall_brick_4": 82,
    "wall_brick_5": 83,
    "wall_brick_6": 84,
    "wall_brick_7": 85,
    "wall_stone_0": 86,
    "wall_stone_1": 87,
    "wall_stone_2": 88,
    "wall_stone_3": 89,
    "wall_stone_4": 90,
    "wall_stone_5": 91,
    "wall_stone_6": 92,
    "wall_stone_7": 93,
    "wall_stone_8": 94,
    "wall_stone_9": 95,
    "wall_crypt_0": 96,
    "wall_crypt_1": 97,
    "wall_crypt_2": 98,
    "wall_crypt_3": 99,
    "wall_crypt_4": 100,
    "wall_crypt_5": 101,
    "wall_crypt_6": 102,
    "wall_crypt_7": 103,
    "wall_sand_0": 104,
    "wall_sand_1": 105,
    "wall_sand_2": 106,
    "wall_sand_3": 107,
    "wall_sand_4": 108,
    "wall_sand_5": 109,
    "wall_sand_6": 110,
    "wall_sand_7": 111,
    "wall_sand_8": 112,
    "wall_sand_9": 113,
    "wall_marble_0": 114,
    "wall_marble_1": 115,
    "wall_marble_2": 116,
    "wall_marble_3": 117,
    "wall_marble_4": 118,
    "wall_marble_5": 119,
    "wall_volcanic_0": 120,
    "wall_volcanic_1": 121,
    "wall_volcanic_2": 122,
    "wall_volcanic_3": 123,
    "wall_volcanic_4": 124,
    "wall_volcanic_5": 125,
    "wall_volcanic_6": 126,
    "wall_relief_0": 127,
    "wall_relief_1": 128,
    "wall_relief_2": 129,
    "wall_relief_3": 130,
    "wall_relief_4": 131,
    "wall_relief_5": 132,
    "wall_relief_6": 133,
    "wall_relief_7": 134,
    "wall_vines_0": 135,
    "wall_vines_1": 136,
    "wall_vines_2": 137,
    "door_closed": 138,
    "door_open": 139,
    "door_broken": 140,
    "door_runed": 141,
    "door_closed_crypt": 142,
    "door_broken_crypt": 143,
    "stairs_up": 144,
    "stairs_down": 145,
    "hatch_up": 146,
    "hatch_down": 147,
    "stairs_up_metal": 148,
    "stairs_down_metal": 149,
    "portal": 150,
    "exit_portal": 151,
    "tree_tree_0": 152,
    "tree_tree_1": 153,
    "tree_tree_2": 154,
    "tree_tree_3": 155,
    "tree_tree_4": 156,
    "tree_tree_5": 157,
    "tree_tree_dead_0": 158,
    "tree_tree_dead_1": 159,
    "tree_tree_petrified_0": 160,
    "tree_tree_petrified_1": 161,
    "statue_angel": 162,
    "statue_archer": 163,
    "statue_dragon": 164,
    "fountain_blue": 165,
    "fountain_blood": 166,
    "fountain_sparkling": 167,
    "fountain_dry": 168,
    "grate": 169,
    "altar_generic_0": 170,
    "altar_generic_1": 171,
    "altar_generic_2": 172,
    "altar_generic_3": 173,
    "altar_generic_4": 174,
    "altar_generic_5": 175,
    "sarcophagus": 176,
    "flowers_0": 177,
    "flowers_1": 178,
    "flowers_2": 179,
    "flowers_3": 180,
    "floor_decorative": 181,
    "rock_depleted": 182,
    "rock_copper": 183,
    "rock_tin": 184
  },
  "groups": {
    "floor": {
      "stone": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8
      ],
      "grey": [
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16
      ],
      "crypt": [
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24
      ],
      "sand": [
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34
      ],
      "volcanic": [
        35,
        36,
        37,
        38,
        39,
        40,
        41
      ],
      "marsh": [
        42,
        43,
        44,
        45
      ],
      "mud": [
        46,
        47,
        48,
        49
      ],
      "ice": [
        50,
        51,
        52,
        53
      ],
      "lair": [
        54,
        55,
        56,
        57
      ],
      "blood": [
        58,
        59,
        60,
        61
      ],
      "dirt": [
        62,
        63,
        64
      ],
      "marble": [
        65,
        66,
        67,
        68,
        69,
        70
      ],
      "tomb": [
        71,
        72,
        73,
        74
      ]
    },
    "liquid": {
      "water_shallow": [
        75
      ],
      "water_deep": [
        76
      ],
      "water_murky": [
        77
      ]
    },
    "wall": {
      "brick": [
        78,
        79,
        80,
        81,
        82,
        83,
        84,
        85
      ],
      "stone": [
        86,
        87,
        88,
        89,
        90,
        91,
        92,
        93,
        94,
        95
      ],
      "crypt": [
        96,
        97,
        98,
        99,
        100,
        101,
        102,
        103
      ],
      "sand": [
        104,
        105,
        106,
        107,
        108,
        109,
        110,
        111,
        112,
        113
      ],
      "marble": [
        114,
        115,
        116,
        117,
        118,
        119
      ],
      "volcanic": [
        120,
        121,
        122,
        123,
        124,
        125,
        126
      ],
      "relief": [
        127,
        128,
        129,
        130,
        131,
        132,
        133,
        134
      ],
      "vines": [
        135,
        136,
        137
      ]
    },
    "door": {
      "door_closed": [
        138
      ],
      "door_open": [
        139
      ],
      "door_broken": [
        140
      ],
      "door_runed": [
        141
      ],
      "door_closed_crypt": [
        142
      ],
      "door_broken_crypt": [
        143
      ]
    },
    "gateway": {
      "stairs_up": [
        144
      ],
      "stairs_down": [
        145
      ],
      "hatch_up": [
        146
      ],
      "hatch_down": [
        147
      ],
      "stairs_up_metal": [
        148
      ],
      "stairs_down_metal": [
        149
      ],
      "portal": [
        150
      ],
      "exit_portal": [
        151
      ]
    },
    "tree": {
      "tree": [
        152,
        153,
        154,
        155,
        156,
        157
      ],
      "tree_dead": [
        158,
        159
      ],
      "tree_petrified": [
        160,
        161
      ]
    },
    "decor": {
      "statue_angel": [
        162
      ],
      "statue_archer": [
        163
      ],
      "statue_dragon": [
        164
      ],
      "fountain_blue": [
        165
      ],
      "fountain_blood": [
        166
      ],
      "fountain_sparkling": [
        167
      ],
      "fountain_dry": [
        168
      ],
      "grate": [
        169
      ],
      "altar_generic": [
        170,
        171,
        172,
        173,
        174,
        175
      ],
      "sarcophagus": [
        176
      ]
    },
    "decor_walk": {
      "flowers": [
        177,
        178,
        179,
        180
      ],
      "floor_decorative": [
        181
      ]
    },
    "resource": {
      "rock_depleted": [
        182
      ],
      "rock_copper": [
        183
      ],
      "rock_tin": [
        184
      ]
    }
  },
  "blockedBg": [
    75,
    76,
    77,
    78,
    79,
    80,
    81,
    82,
    83,
    84,
    85,
    86,
    87,
    88,
    89,
    90,
    91,
    92,
    93,
    94,
    95,
    96,
    97,
    98,
    99,
    100,
    101,
    102,
    103,
    104,
    105,
    106,
    107,
    108,
    109,
    110,
    111,
    112,
    113,
    114,
    115,
    116,
    117,
    118,
    119,
    120,
    121,
    122,
    123,
    124,
    125,
    126,
    127,
    128,
    129,
    130,
    131,
    132,
    133,
    134,
    135,
    136,
    137
  ],
  "walkableFg": [
    139,
    140,
    143,
    144,
    145,
    146,
    147,
    148,
    149,
    150,
    151,
    177,
    178,
    179,
    180,
    181
  ]
};

export const DUNGEON_FIRST_GID = DUNGEON_TILESET.firstGid;
export const dungeonGid = name => {
  const local = DUNGEON_TILESET.names[name];
  return typeof local === 'number' ? DUNGEON_TILESET.firstGid + local : 0;
};
export const dungeonGroupGids = (category, variant) => {
  const group = DUNGEON_TILESET.groups[category];
  const ids = group && group[variant] ? group[variant] : [];
  return ids.map(id => DUNGEON_TILESET.firstGid + id);
};

export default DUNGEON_TILESET;
